apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: darboon
  namespace: darboon
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts: [auth.example.com]
      secretName: darboon-tls
  rules:
    - host: auth.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: darboon-api
                port:
                  number: 3000
